# Site settings
title: La Hackería
email: rwilhelmy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bricolage digital de hacks y retórica barata
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rodowi
github_username:  rodowi

# Build settings
markdown: kramdown
